// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLTlKrSAn6hj1xg0gAik--XnQ8TS5IoTg',
    appId: '1:651117059267:web:c065073fd6f34cbd74d676',
    messagingSenderId: '651117059267',
    projectId: 'bhavin-d149e',
    authDomain: 'bhavin-d149e.firebaseapp.com',
    storageBucket: 'bhavin-d149e.appspot.com',
    measurementId: 'G-NFKX04KXJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC22-kpKYaIbI67zAWwoZx3DLLObLThkFc',
    appId: '1:651117059267:android:8ea9e158e681925974d676',
    messagingSenderId: '651117059267',
    projectId: 'bhavin-d149e',
    storageBucket: 'bhavin-d149e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdpzLuDrVyh9xtndxfISTeGUt7AjZC8Y',
    appId: '1:651117059267:ios:39098b3af2c5889c74d676',
    messagingSenderId: '651117059267',
    projectId: 'bhavin-d149e',
    storageBucket: 'bhavin-d149e.appspot.com',
    iosClientId: '651117059267-eim546aa2e42c99lvjjqo9p2rkpcqfeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhavin',
  );
}
